server:  port: 8080
  
spring:  application:    name: api-gateway-service

eureka:         #tells about the Eureka server details and its refresh time  instance:    leaseRenewalIntervalInSeconds: 1    leaseExpirationDurationInSeconds: 2  client:    serviceUrl:      defaultZone: http://localhost:8761/eureka/    healthcheck:      enabled: true    lease:      duration: 5      zuul:  routes:    book-service:      serviceId:book-service    subscription-service:      serviceId:subscription-service